[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
bcrypt = "0.12.3"
log = "0.4"
env_logger = "0.10"